INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (0, "Сила атаки +2", 1, 1, 2, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (1, "Сила атаки +5", 1, 1, 5, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (2, "Сила атаки +10", 1, 1, 10, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (3, "Сила атаки +25", 1, 1, 25, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (4, "Точность +3", 1, 3, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (5, "Точность +5", 1, 3, 5, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (6, "Точность +10", 1, 3, 10, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (7, "Шанс крита +2", 1, 5, 2, 60);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (8, "Шанс крита +4", 1, 5, 4, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (9, "Шанс крита +6", 1, 5, 6, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (10, "Шанс крита +8", 1, 5, 8, 9);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (11, "Шанс крита +10", 1, 5, 10, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (12, "Сила атаки +1%", 1, 6, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (13, "Сила атаки +5%", 1, 6, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (14, "Сила атаки +10%", 1, 6, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (15, "Урон от крита +0.05", 1, 8, 5, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (16, "Урон от крита +0.10", 1, 8, 10, 12);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (17, "Урон от крита +0.15", 1, 8, 15, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (18, "Урон от крита +0.20", 1, 8, 20, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (19, "Урон от крита +0.25", 1, 8, 25, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (20, "Поглощение ХП +1%", 1, 11, 1, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (21, "Поглощение ХП +2%", 1, 11, 2, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (22, "Поглощение ХП +3%", 1, 11, 3, 5);

INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (23, "Уклонение +3", 2, 2, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (24, "Уклонение +5", 2, 2, 5, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (25, "Уклонение +10", 2, 2, 10, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (26, "Макс. ХП +1%", 2, 4, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (27, "Макс. ХП +5%", 2, 4, 5, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (28, "Макс. ХП +10%", 2, 4, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (29, "Защита +1%", 2, 7, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (30, "Защита +5%", 2, 7, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (31, "Защита +10%", 2, 7, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (32, "Снижение крит. урона +2%", 2, 9, 2, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (33, "Снижение крит. урона +4%", 2, 9, 4, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (34, "Снижение крит. урона +6%", 2, 9, 6, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (35, "Уменьшить силу крита +0.02", 2, 10, 2, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (36, "Уменьшить силу крита +0.04", 2, 10, 4, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (37, "Уменьшить силу крита +0.06", 2, 10, 6, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (38, "Регенерация +1", 2, 13, 1, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (39, "Регенерация +2", 2, 13, 2, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (40, "Отразить урон +1%", 2, 12, 1, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (41, "Отразить урон +2%", 2, 12, 2, 12);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (42, "Отразить урон +3%", 2, 12, 3, 7);

INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (43, "Уклонение +3", 5, 2, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (44, "Уклонение +5", 5, 2, 5, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (45, "Уклонение +10", 5, 2, 10, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (46, "Макс. ХП +1%", 5, 4, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (47, "Макс. ХП +5%", 5, 4, 5, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (48, "Макс. ХП +10%", 5, 4, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (49, "Защита +1%", 5, 7, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (50, "Защита +5%", 5, 7, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (51, "Защита +10%", 5, 7, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (52, "Снижение крит. урона +2%", 5, 9, 2, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (53, "Снижение крит. урона +4%", 5, 9, 4, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (54, "Снижение крит. урона +6%", 5, 9, 6, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (55, "Уменьшить силу крита +0.02", 5, 10, 2, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (56, "Уменьшить силу крита +0.04", 5, 10, 4, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (57, "Уменьшить силу крита +0.06", 5, 10, 6, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (58, "Регенерация +1", 5, 13, 1, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (59, "Регенерация +2", 5, 13, 2, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (60, "Отразить урон +1%", 5, 12, 1, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (61, "Отразить урон +2%", 5, 12, 2, 12);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (62, "Отразить урон +3%", 5, 12, 3, 7);

INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (63, "Сила атаки +10", 4, 1, 10, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (64, "Сила атаки +20", 4, 1, 20, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (65, "Сила атаки +30", 4, 1, 30, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (66, "Точность +10", 4, 3, 10, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (67, "Уклонение +10", 4, 2, 10, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (68, "Шанс крита +8", 4, 5, 8, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (69, "Шанс крита +10", 4, 5, 10, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (70, "Сила атаки +1%", 4, 6, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (71, "Сила атаки +5%", 4, 6, 5, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (72, "Сила атаки +10%", 4, 6, 10, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (73, "Защита +1%", 4, 7, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (74, "Защита +5%", 4, 7, 5, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (75, "Защита +10%", 4, 7, 10, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (76, "Макс. ХП +1%", 4, 4, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (77, "Макс. ХП +5%", 4, 4, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (78, "Макс. ХП +10%", 4, 4, 10, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (79, "Урон от крита 0.20", 4, 8, 20, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (80, "Урон от крита 0.25", 4, 8, 25, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (81, "Поглощение ХП +2%", 4, 11, 2, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (82, "Поглощение ХП +3%", 4, 11, 3, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (83, "Снижение крит. урона +4%", 4, 9, 4, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (84, "Снижение крит. урона +6%", 4, 9, 6, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (85, "Регенерация +2", 4, 13, 2, 8);

INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (86, "Точность +3", 6, 3, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (87, "Точность +5", 6, 3, 5, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (88, "Точность +10", 6, 3, 10, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (89, "Уклонение +3", 6, 2, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (90, "Уклонение +5", 6, 2, 5, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (91, "Уклонение +10", 6, 2, 10, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (92, "Макс. ХП +1%", 6, 4, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (93, "Макс. ХП +5%", 6, 4, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (94, "Макс. ХП +10%", 6, 4, 10, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (95, "Шанс крита +1", 6, 5, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (96, "Шанс крита +2", 6, 5, 2, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (97, "Шанс крита +3", 6, 5, 3, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (98, "Шанс крита +4", 6, 5, 4, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (99, "Шанс крита +5", 6, 5, 5, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (100, "Шанс крита +6", 6, 5, 6, 9);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (101, "Шанс крита +7", 6, 5, 7, 7);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (102, "Шанс крита +8", 6, 5, 8, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (103, "Шанс крита +9", 6, 5, 9, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (104, "Шанс крита +10", 6, 5, 10, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (105, "Сила атаки +1%", 6, 6, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (106, "Сила атаки +2%", 6, 6, 2, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (107, "Сила атаки +3%", 6, 6, 3, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (108, "Сила атаки +4%", 6, 6, 4, 25);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (109, "Сила атаки +5%", 6, 6, 5, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (110, "Сила атаки +6%", 6, 6, 6, 7);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (111, "Сила атаки +7%", 6, 6, 7, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (112, "Сила атаки +8%", 6, 6, 8, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (113, "Сила атаки +9%", 6, 6, 9, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (114, "Сила атаки +10%", 6, 6, 10, 1);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (115, "Урон от крита +0.02", 6, 8, 2, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (116, "Урон от крита +0.04", 6, 8, 4, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (117, "Урон от крита +0.06", 6, 8, 6, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (118, "Урон от крита +0.08", 6, 8, 8, 25);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (119, "Урон от крита +0.10", 6, 8, 10, 8);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (120, "Урон от крита +0.12", 6, 8, 12, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (121, "Урон от крита +0.14", 6, 8, 14, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (122, "Урон от крита +0.16", 6, 8, 16, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (123, "Урон от крита +0.18", 6, 8, 18, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (124, "Урон от крита +0.20", 6, 8, 20, 1);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (125, "Уменьшить силу крита +0.03", 6, 10, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (126, "Уменьшить силу крита +0.06", 6, 10, 6, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (127, "Уменьшить силу крита +0.09", 6, 10, 9, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (128, "Уменьшить силу крита +0.12", 6, 10, 12, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (129, "Уменьшить силу крита +0.15", 6, 10, 15, 8);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (130, "Уменьшить силу крита +0.18", 6, 10, 18, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (131, "Уменьшить силу крита +0.21", 6, 10, 21, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (132, "Уменьшить силу крита +0.24", 6, 10, 24, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (133, "Уменьшить силу крита +0.27", 6, 10, 27, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (134, "Уменьшить силу крита +0.30", 6, 10, 30, 1);

INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (135, "Точность +3", 7, 3, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (136, "Точность +5", 7, 3, 5, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (137, "Точность +10", 7, 3, 10, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (138, "Уклонение +3", 7, 2, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (139, "Уклонение +5", 7, 2, 5, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (140, "Уклонение +10", 7, 2, 10, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (141, "Макс. ХП +1%", 7, 4, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (142, "Макс. ХП +5%", 7, 4, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (143, "Макс. ХП +10%", 7, 4, 10, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (144, "Шанс крита +1", 7, 5, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (145, "Шанс крита +2", 7, 5, 2, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (146, "Шанс крита +3", 7, 5, 3, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (147, "Шанс крита +4", 7, 5, 4, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (148, "Шанс крита +5", 7, 5, 5, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (149, "Шанс крита +6", 7, 5, 6, 9);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (150, "Шанс крита +7", 7, 5, 7, 7);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (151, "Шанс крита +8", 7, 5, 8, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (152, "Шанс крита +9", 7, 5, 9, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (153, "Шанс крита +10", 7, 5, 10, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (154, "Сила атаки +1%", 7, 6, 1, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (155, "Сила атаки +2%", 7, 6, 2, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (156, "Сила атаки +3%", 7, 6, 3, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (157, "Сила атаки +4%", 7, 6, 4, 25);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (158, "Сила атаки +5%", 7, 6, 5, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (159, "Сила атаки +6%", 7, 6, 6, 7);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (160, "Сила атаки +7%", 7, 6, 7, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (161, "Сила атаки +8%", 7, 6, 8, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (162, "Сила атаки +9%", 7, 6, 9, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (163, "Сила атаки +10%", 7, 6, 10, 1);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (164, "Урон от крита +0.02", 7, 8, 2, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (165, "Урон от крита +0.04", 7, 8, 4, 70);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (166, "Урон от крита +0.06", 7, 8, 6, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (167, "Урон от крита +0.08", 7, 8, 8, 25);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (168, "Урон от крита +0.10", 7, 8, 10, 8);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (169, "Урон от крита +0.12", 7, 8, 12, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (170, "Урон от крита +0.14", 7, 8, 14, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (171, "Урон от крита +0.16", 7, 8, 16, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (172, "Урон от крита +0.18", 7, 8, 18, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (173, "Урон от крита +0.20", 7, 8, 20, 1);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (174, "Уменьшить силу крита +0.03", 7, 10, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (175, "Уменьшить силу крита +0.06", 7, 10, 6, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (176, "Уменьшить силу крита +0.09", 7, 10, 9, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (177, "Уменьшить силу крита +0.12", 7, 10, 12, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (178, "Уменьшить силу крита +0.15", 7, 10, 15, 8);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (179, "Уменьшить силу крита +0.18", 7, 10, 18, 6);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (180, "Уменьшить силу крита +0.21", 7, 10, 21, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (181, "Уменьшить силу крита +0.24", 7, 10, 24, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (182, "Уменьшить силу крита +0.27", 7, 10, 27, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (183, "Уменьшить силу крита +0.30", 7, 10, 30, 1);

INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (184, "Уклонение +3", 3, 2, 3, 100);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (185, "Уклонение +5", 3, 2, 5, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (186, "Уклонение +10", 3, 2, 10, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (187, "Макс. ХП +1%", 3, 4, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (188, "Макс. ХП +5%", 3, 4, 5, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (189, "Макс. ХП +10%", 3, 4, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (190, "Защита +1%", 3, 7, 1, 50);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (191, "Защита +5%", 3, 7, 5, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (192, "Защита +10%", 3, 7, 10, 3);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (193, "Снижение крит. урона +2%", 3, 9, 2, 20);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (194, "Снижение крит. урона +4%", 3, 9, 4, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (195, "Снижение крит. урона +6%", 3, 9, 6, 2);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (196, "Уменьшить силу крита +0.02", 3, 10, 2, 40);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (197, "Уменьшить силу крита +0.04", 3, 10, 4, 15);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (198, "Уменьшить силу крита +0.06", 3, 10, 6, 5);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (199, "Регенерация +1", 3, 13, 1, 10);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (200, "Регенерация +2", 3, 13, 2, 4);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (201, "Отразить урон +1%", 3, 12, 1, 30);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (202, "Отразить урон +2%", 3, 12, 2, 12);
INSERT INTO `stats_info`(`Stat`, `Text`, `StatType`, `StatEnum`, `Value`, `Chance`) VALUES (203, "Отразить урон +3%", 3, 12, 3, 7);